s="suriya Anand is a devil maker"
print("given string",s)
print("Uppercase",s.upper())
print("lowercase",s.lower())
a=len(s)
print("length of string",a)
s_trim=len(s.strip())
s_tirm=len(s.rstrip())
s_tirm=len(s.lstrip())
print("length of string tirm",s_tirm)
print("length of string tirm",s_tirm)
print("length of string tirm",s_tirm)
s=s.strip()
print(s[1:5])
print(s[0:8])
print(s[6:9])
print(s[1:2:9])
